#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cesium"
name = "Cesium"
description.en = "Duniter client to manage wallets, certifications in a libre money"
description.fr = "Client Duniter pour gérer ses portes-monnaie, les certifications au sein d’une monnaie libre"

version = "1.7.15~ynh1"

maintainers = ["Moul"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://cesium.app"
code = "https://github.com/duniter/cesium"

[integration]
yunohost = ">= 11.2.0"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/cesium"

    [install.init_main_permission]
    help.en = "If it is a public application, there will not have authentification"
    help.fr = "Si l'application est publique, il n'y aura pas d'authentification"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/duniter/cesium/releases/download/v1.7.15/cesium-v1.7.15-web.zip"
    sha256 = "4c92d2bcdf89ac31d36677cd46f97a94168af594aba53f31691bb4fa5014bd78"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^cesium-v.*-web\\.zip$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
