#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)

# Remove sources
ynh_secure_remove /var/www/$app

# Remove configuration files
rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Reload nginx service
service nginx reload
