#!/bin/bash

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Retrieve app settings
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)

# Remove sources
sudo rm -rf /var/www/$app

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Resload nginx service
sudo service nginx reload
